### ISSUE TITLE
Original dataset is currently unavailable

### ISSUE THREAD

**Issue by WinterShiver** [uds-lsv/NoisyNER#1]
The link for the original Estonian NER dataset is currently unavailable. Is there any other methods to download the dataset?

**Comment by WinterShiver** [comment]
Happily found that it could be downloaded at [link](https://code.google.com/archive/p/patnlp/downloads).

**Comment by michael-aloys** [comment]
Thanks a lot for letting us know. We have updated the README accordingly and we will reach out to the original authors.
