### ISSUE TITLE
request for the dataset

### ISSUE THREAD

**Issue by hhf-hd** [uds-lsv/NoisyNER#2]
hello,thanks for your work ,but the link to the dataset is not valid,can you fix it or upload to github?
many thanks !

**Comment by michael-aloys** [comment]
Hi,

sorry that the dataset is not available. There seems to be an issue with the platform of the authors of the original dataset we are based on. You can still download the estner.cnll.zip file here: https://code.google.com/archive/p/patnlp/downloads

**Comment by michael-aloys** [comment]
I've updated the README accordingly. Please let me know if you have any other issues.
